-- what is the total revenue generated by male vs female customers
select gender, sum(purchase_amount) as total_revenue 
from customers
group by gender;

-- which customer used discount but still spent more than the avg purchase amount
select customer_id,purchase_amount 
from customers 
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customers)

-- which are top 5 products with the highest avg review rating
select item_purchased,round(avg(review_rating),2) as average_product_rating
from customers
group by item_purchased
order by average_product_rating desc
limit 5

-- compare avg purchase amount between standard and express shipping
select shipping_type,
avg(purchase_amount)
from customers
where shipping_type in('Standard','Express')
group by shipping_type


-- do subscribed customers spend more? compare avg spend and total revenue between sub and non-sub
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customers
group by subscription_status
order by avg_spend , total_revenue desc

-- which 5 products have highest percentage of purchases with discount applied
select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end) / count(*) ,2) as discount_rate
from customers
group by item_purchased
order by discount_rate desc
limit 5

-- segment customers into new,returning,loyal based on there total number of previous purchase and show the count of each segment
with customer_type as(
select customer_id, previous_purchases,
case 
     when previous_purchases = 1 then 'New'
     when previous_purchases between 2 and 10 then 'Returning'
     else 'Loyal'
     end as customer_segment
from customers
)

select customer_segment , count(*) as 'number_of_customers'
from customer_type
group by customer_segment


-- what are top 3 most purchased product within each category
with item_counts as(
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank 
from customers
group by category, item_purchased
)

select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <= 3

-- are customers who are repeat buyers (more than 5 previous purchase) also likely to subscribe
select subscription_status,
count(customer_id) as total_buyers
from customers
where previous_purchases > 5
group by subscription_status

-- what is revenue contribution of each age group
select age_group,
sum(purchase_amount) as total_revenue
from customers
group by age_group
order by total_revenue desc




